openapi: '3.0.2'
info:
  title: What to watch
  version: '1.0'
paths:
  /user/{id}:
    summary: 'Logs in the user.'
    delete:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: User deleted.
        '404':
          description: Invalid id, not found.
  /user:
    post:
      requestBody:
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/Login'
      responses:
        '201':
          description: User created and logged in.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '409':
          description: Username taken.
    get:
      description: Get all users.
      responses:
        '200':
          description: List of all users.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
  /list/{id}:
    get:
      description: 'Gets given list owned by user.'
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Success.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WatchList'
        '401':
          description: 'User must be logged in to see their list.'
        '403':
          description: User is not owner.
        '404':
          description: WatchList not found.
    delete:
      description: 'Deletes list with given id.'
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Success.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WatchList'
        '401':
          description: 'User must be logged in to delete their list.'
        '403':
          description: User is not owner.
        '404':
          description: WatchList not found.
  /list/{id}/add:  
    put:
      description: 'Adds Movie to WatchList with given id.'
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: movieId
          in: query
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: 'List updated.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WatchList'
        '404':
          description: 'Not found.'
        '401':
          description: 'User must be logged in to update their list.'
        '403':
          description: 'User can only edit list that belongs to them.'
  /list/{id}/remove:  
    put:
      description: 'Removes Movie to WatchList with given id.'
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: movieId
          in: query
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: 'List updated.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WatchList'
        '404':
          description: 'Not found.'
        '401':
          description: 'User must be logged in to update their list.'
        '403':
          description: 'User can only edit list that belongs to them.'
  /list:
    post:
      description: 'Creates new Watch List.'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WatchList'
      responses:
        '201':
          description: List created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WatchList'
        '401':
          description: 'User must be logged in to create list.'
        '400':
          description: 'List cannot be created.'
    get:
      description: 'Gets all WatchLists for current user.'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WatchList'
        '401':
          description: 'User must be logged in to see their lists.'
  /movie/{id}:
    get:
      description: 'Finds movie with given ID'
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 'Success.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
        '404':
          description: 'Not found.'
  /movie/now:
    get:
      description: 'Finds best newest movies.'
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Movie'
components:
  schemas:
    User:
      type: object
      properties:
        id: 
          type: integer
          format: int64
          example: 10
        username:
          type: string
        isAdmin:
          type: boolean
    Login:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    Movie:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        releaseDate:
          type: string
        trailer:
          type: string #iframe
        genres:
          type: array
          items:
            type: string
        popularity:
          type: number
          format: float
    WatchList:
      type: object
      properties:
        id: 
          type: integer
          format: int64
        title:
          type: string
        movies:
          type: array
          items:
            $ref: '#/components/schemas/Movie'
        
        

        

